# Generated by Django 5.2.6 on 2025-10-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                (
                    "unidade_base",
                    models.CharField(
                        choices=[
                            ("kg", "Quilo (kg)"),
                            ("g", "Grama (g)"),
                            ("mg", "Miligrama (mg)"),
                            ("l", "Litro (l)"),
                            ("dl", "Decilitro (dl)"),
                            ("cl", "Centilitro (cl)"),
                            ("ml", "Mililitro (ml)"),
                            ("cs", "Colher de sopa (~15 ml)"),
                            ("cc", "Colher de chá (~5 ml)"),
                            ("xic", "Xícara (~240 ml)"),
                            ("pt", "Pitada"),
                            ("gt", "Gota"),
                            ("und", "Unidade"),
                            ("dz", "Dúzia"),
                            ("qb", "Quanto baste (q.b.)"),
                        ],
                        default="kg",
                        max_length=5,
                    ),
                ),
                (
                    "custo_por_unidade",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("disciplina", models.CharField(blank=True, max_length=120)),
                ("tipo_coccao", models.CharField(blank=True, max_length=120)),
                ("tempo_coccao_min", models.PositiveIntegerField(default=0)),
                ("tempo_preparo_min", models.PositiveIntegerField(default=0)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="receitas/"),
                ),
                ("modo_preparo", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "rendimento_total",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "unidade_rendimento",
                    models.CharField(
                        choices=[
                            ("kg", "Quilo (kg)"),
                            ("g", "Grama (g)"),
                            ("mg", "Miligrama (mg)"),
                            ("l", "Litro (l)"),
                            ("dl", "Decilitro (dl)"),
                            ("cl", "Centilitro (cl)"),
                            ("ml", "Mililitro (ml)"),
                            ("cs", "Colher de sopa (~15 ml)"),
                            ("cc", "Colher de chá (~5 ml)"),
                            ("xic", "Xícara (~240 ml)"),
                            ("pt", "Pitada"),
                            ("gt", "Gota"),
                            ("und", "Unidade"),
                            ("dz", "Dúzia"),
                            ("qb", "Quanto baste (q.b.)"),
                        ],
                        default="kg",
                        max_length=5,
                    ),
                ),
                (
                    "peso_por_porcao",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receitas",
                        to="fichas.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("kg", "Quilo (kg)"),
                            ("g", "Grama (g)"),
                            ("mg", "Miligrama (mg)"),
                            ("l", "Litro (l)"),
                            ("dl", "Decilitro (dl)"),
                            ("cl", "Centilitro (cl)"),
                            ("ml", "Mililitro (ml)"),
                            ("cs", "Colher de sopa (~15 ml)"),
                            ("cc", "Colher de chá (~5 ml)"),
                            ("xic", "Xícara (~240 ml)"),
                            ("pt", "Pitada"),
                            ("gt", "Gota"),
                            ("und", "Unidade"),
                            ("dz", "Dúzia"),
                            ("qb", "Quanto baste (q.b.)"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "peso_bruto",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "peso_liquido",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "fator_correcao",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("medida_caseira", models.CharField(blank=True, max_length=60)),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fichas.ingrediente",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="fichas.receita",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponenteReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("kg", "Quilo (kg)"),
                            ("g", "Grama (g)"),
                            ("mg", "Miligrama (mg)"),
                            ("l", "Litro (l)"),
                            ("dl", "Decilitro (dl)"),
                            ("cl", "Centilitro (cl)"),
                            ("ml", "Mililitro (ml)"),
                            ("cs", "Colher de sopa (~15 ml)"),
                            ("cc", "Colher de chá (~5 ml)"),
                            ("xic", "Xícara (~240 ml)"),
                            ("pt", "Pitada"),
                            ("gt", "Gota"),
                            ("und", "Unidade"),
                            ("dz", "Dúzia"),
                            ("qb", "Quanto baste (q.b.)"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="fichas.receita",
                    ),
                ),
                (
                    "sub_receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="como_componente",
                        to="fichas.receita",
                    ),
                ),
            ],
        ),
    ]
