# Generated by Django 5.2.6 on 2025-10-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receita",
            name="foto",
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto ilustrativa do ingrediente",
                null=True,
                upload_to="ingredientes/",
            ),
        ),
        migrations.AddField(
            model_name="receita",
            name="foto_preparo",
            field=models.ImageField(
                blank=True,
                help_text="Imagem do prato final ou preparo",
                null=True,
                upload_to="receitas/",
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="disciplina",
            field=models.CharField(
                blank=True, help_text="Ex.: Cozinha Fria, Padaria", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="tipo_coccao",
            field=models.CharField(
                blank=True,
                help_text="Ex.: Processador, Assar, Cozinhar",
                max_length=120,
            ),
        ),
    ]
