# Generated by Django 5.2.6 on 2025-10-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipe", "0001_initial"),
        ("fichas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("data", models.DateField()),
                ("numero_pessoas", models.PositiveIntegerField()),
                (
                    "custo_indireto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "margem_lucro",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCardapio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcoes_por_pessoa",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="eventos.evento",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fichas.receita"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipacaoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "horas",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "valor_hora",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participacoes",
                        to="eventos.evento",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipe.funcaoequipe",
                    ),
                ),
            ],
        ),
    ]
