# Generated by Django 5.2.6 on 2025-10-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcardapio",
            name="foto_item",
            field=models.ImageField(
                blank=True,
                help_text="Foto do prato servido no evento (opcional).",
                null=True,
                upload_to="itens_cardapio/",
            ),
        ),
    ]
